version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: /DockerHub/UserName
    DOCKERHUB_ACCESSTOKEN: /DockerHub/AccessToken
  variables:
    REGION: ap-northeast-1
    ECR_REPOSITORY_NAME: shogi/sample/test01

phases:
  # install:
  #   runtime-versions:
  #     python: 3.12
  #   commands:
  #     - pip3 install -r requirements.txt
  pre_build:
    commands:
      - export ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "Using AWS Account ID:" $ACCOUNT_ID
      - curl -LS -o nn.7z https://github.com/yaneurao/YaneuraOu/releases/download/suisho5/Suisho5.7z
      - 7z x nn.7z
      - ls
      - mkdir -p ShogiCPU/Engine/eval
      - mv nn.bin ShogiCPU/Engine/eval/
      - sed -i 's/^COMPILER = clang++/#COMPILER = clang++/' ShogiCPU/YaneuraOu/source/Makefile
      - sed -i 's/^#COMPILER = g++/COMPILER = g++/' ShogiCPU/YaneuraOu/source/Makefile
      - sed -i 's/^TARGET_CPU = AVX2/#TARGET_CPU = AVX2/' ShogiCPU/YaneuraOu/source/Makefile
      - sed -i 's/^#TARGET_CPU = SSE42/TARGET_CPU = SSE42/' ShogiCPU/YaneuraOu/source/Makefile
      - |
        if ! aws ecr describe-repositories --repository-names "$ECR_REPOSITORY_NAME" --region $REGION > /dev/null 2>&1; then
          echo "ECR repository not found. Creating $ECR_REPOSITORY_NAME ..."
          aws ecr create-repository --repository-name "$ECR_REPOSITORY_NAME" --region $REGION
        else
          echo "ECR repository $ECR_REPOSITORY_NAME already exists."
        fi
      - echo "$DOCKERHUB_ACCESSTOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  build:
    commands:
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --image-repository $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY_NAME
